---
 
- name: Install Elasticsearch
  hosts: elastic    
  roles: 
    - elastic

- name: Install Kibana
  hosts: kibana
  roles: 
    - kibana

- name: Install Filebeat
  hosts: filebeat
  roles: 
    - filebeat
